# syntax=docker/dockerfile:1
FROM python:3.11
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# ENV POSTGRES_NAME=postgres
# ENV POSTGRES_USER=postgres
# ENV POSTGRES_PASSWORD=postgres

WORKDIR /tg_bot
COPY . /tg_bot/
ENV PATH="/tg_bot/.venv/bin:$PATH"
RUN pip install -r requirements.txt
RUN apt update && apt install libpq-dev
CMD ["python", "bot.py" ]